s2e-obj-y += ConfigFile.o ExprInterface.o \
	MMUFunctionHandlers.o Plugin.o \
	S2E.o S2EDeviceState.o \
	S2EExecutionState.o S2EExecutor.o S2EStatsTracker.o \
	SelectRemovalPass.o Slab.o Synchronization.o \

#s2e-obj-y +=   QemuSocket.o
obj-y += $(s2e-obj-y)
