s2e-obj-y += TestOnTranslateBlockStart.o \
	TestOnTranslateBlockEnd.o \
        TestOnTranslateInstructionStart.o \
        TestOnTranslateInstructionEnd.o \
        TestOnExecuteBlockStart.o \
        TestOnExecuteBlockEnd.o \
        TestOnExecuteInstructionStart.o \
        TestOnExecuteInstructionEnd.o
